# Generated by Django 3.2 on 2022-09-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='billDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
