# Generated by Django 3.2 on 2022-09-01 16:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_billing_billdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='billDate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
