# Generated by Django 3.2 on 2022-09-01 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0008_staff_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='user',
        ),
        migrations.AddField(
            model_name='staff',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
