# Generated by Django 3.2 on 2022-09-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0011_auto_20220901_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='staff',
        ),
        migrations.AlterField(
            model_name='billing',
            name='status',
            field=models.CharField(choices=[('PAID', 'PAID'), ('UNPAID', 'UNPAID')], max_length=255, null=True),
        ),
    ]
