# Generated by Django 3.2 on 2022-09-01 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0014_alter_vendor_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='status',
            field=models.CharField(choices=[('UNPAID', 'UNPAID'), ('PAID', 'PAID')], max_length=255, null=True),
        ),
    ]
