# Generated by Django 3.2 on 2022-09-01 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0016_auto_20220901_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='customer_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_name', to='adminpanel.customer'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='status',
            field=models.CharField(choices=[('UNPAID', 'UNPAID'), ('PAID', 'PAID')], max_length=255, null=True),
        ),
    ]
