# Generated by Django 4.1 on 2022-09-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminpanel", "0019_auto_20220901_2047"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billing",
            name="status",
            field=models.CharField(
                choices=[("PAID", "PAID"), ("UNPAID", "UNPAID")],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "ACTIVE"), ("INACTIVE", "INACTIVE")],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "ACTIVE"), ("INACTIVE", "INACTIVE")],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "ACTIVE"), ("INACTIVE", "INACTIVE")],
                max_length=255,
                null=True,
            ),
        ),
    ]
