# Generated by Django 4.1 on 2022-09-02 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("adminpanel", "0022_alter_billing_status_expense"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billing",
            name="status",
            field=models.CharField(
                choices=[("PAID", "PAID"), ("UNPAID", "UNPAID")],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vendor",
                to="adminpanel.vendor",
            ),
        ),
    ]
