from django.urls import path, include

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("viewinventory", views.InventoryView.as_view(),
         name="inventoryView"),
    path("addinventory", views.AddInventoryView.as_view(),
         name="addinventory"),
    path("addbilling", views.AddBillingView.as_view(),
         name="addbilling"),
    path("billinghistory", views.BillingHistoryView.as_view(),
         name="billinghistory"),
    path("expense", views.ExpenseView.as_view(),
         name="expense"),
    path("salary", views.SalaryView.as_view(),
         name="salary"),
    path("pendingbills", views.PendingBillsView.as_view(),
         name="pendingbills"),
    path("viewunpaidbill", views.ViewPendingBillsView.as_view(),
         name="viewunpaidbill"),
    path("vendor", views.VendorView.as_view(),
         name="vendor"),
    path("viewvendor", views.ViewVendorView.as_view(),
         name="viewvendor"),
    path("addvendor", views.AddVendorView.as_view(),
         name="addvendor"),
    path("staff", views.StaffView.as_view(),
         name="staff"),
    path("addstaff", views.AddStaffView.as_view(),
         name="addstaff"),
    path("viewstaff", views.ViewStaffView.as_view(),
         name="viewstaff"),
    path("customer", views.CustomerView.as_view(),
         name="customer"),
    path("addcustomer", views.AddCustomerView.as_view(),
         name="addcustomer"),
    path("viewitem", views.ItemView.as_view(),
         name="viewitem"),
    path("addstock", views.AddStockView.as_view(),
         name="addstock"),
    path("viewbill", views.BillView.as_view(),
         name="viewbill"),
    path("viewsalary", views.ViewSalaryView.as_view(),
         name="viewsalary"),
    path("editexpense", views.EditExpenseView.as_view(),
         name="editexpense"),
    path("viewexpense", views.ViewExpenseView.as_view(),
         name="viewexpense"),
]
